### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pmatseykanets** [jjpmann/real-magnet-sdk#10]
- [x] Add CHANGELOG.md.
- [x] Add CONTRIBUTING.md.
- [x] Add LICENSE.md.
- [x] Update README.md.
- [ ] Update CHANGELOG.md.
- [ ] Document current progress.
- [ ] Add Examples to README.md.
- [ ] Create list of missing endpoints.
- [ ] TBD
